Add Icon and Create splash screen
MosPolyNavigation/iOSApp pull request #2
Opened 2024-04-08 07:10 UTC by miv-dev

2024-04-14 16:24 UTC, asilyk requested changes

2024-04-14 16:24 UTC, asilyk commented on .gitignore
> +!*.xcodeproj/project.pbxproj
project.pbxproj точно стоит игнорить?

2024-04-14 16:24 UTC, asilyk commented on Poly Nav/.DS_Store
.DS_Store в репо быть не должен, это вспомогательный файл для Finder

2024-04-14 16:24 UTC, asilyk commented on Poly Nav/Resources/.DS_Store
.DS_Store в репо быть не должен, это вспомогательный файл для Finder

2024-04-14 16:24 UTC, asilyk commented on Poly Nav/Resources/Assets.xcassets/.DS_Store
.DS_Store в репо быть не должен, это вспомогательный файл для Finder

2024-04-14 16:24 UTC, asilyk commented on Poly Nav/Resources/Assets.xcassets/AppIcon.appiconset/icon-2.png
нужно будет потом поменять, это устаревшее лого

2024-04-14 16:24 UTC, asilyk commented on Poly Nav/Resources/Assets.xcassets/SplashIcon.imageset/icon-2 1.png
нужно будет потом поменять, это устаревшее лого

2024-04-14 16:24 UTC, asilyk commented on Poly Nav/Resources/Assets.xcassets/SplashIcon.imageset/icon-2.png
нужно будет потом поменять, это устаревшее лого

2024-04-14 16:24 UTC, asilyk commented on Poly Nav/Resources/Assets.xcassets/SplashIcon.imageset/icon.png
нужно будет потом поменять, это устаревшее лого

2024-04-21 19:16 UTC, miv-dev commented on .gitignore
> +!*.xcodeproj/project.pbxproj
Я читал, говорят что не нужен

2024-04-21 19:32 UTC, asilyk approved these changes

2024-04-21 19:33 UTC, merged